- ament_package/template/package_level/local_setup.sh.in
> adding more quotes to work with paths including whitespaces

- ament_package/template/environment_hook/path.bat
- ament_package/template/environment_hook/path.sh
The PR adds the environent hooks used by ament_tools#34
@esteve @jacquelinekay @tfoote @wjwwood Please review.
> set PATH for Python packages

- ament_package/template/prefix_level/setup.bat.in
- ament_package/template/prefix_level/setup.sh.in
This bug prevented parent workspaces to be sourced
> fix workspace chaining when sourcing downstream workspace

- ament_package/template/prefix_level/local_setup.bat.in
- ament_package/template/prefix_level/setup.bat.in
> make the prefix level setup.bat file actually .bat

- ament_package/template/package_level/local_setup.bat.in
- ament_package/template/prefix_level/setup.bat.in
> fix spaces in path on Windows

- ament_package/template/prefix_level/local_setup.sh.in
- ament_package/template/prefix_level/setup.sh.in
> fix handling of paths with spaces when collecting environment hooks

- ament_package/template/isolated_prefix_level/local_setup.bat.in
> fix isolated local_setup.bat

- ament_package/template/environment_hook/path.bat
- ament_package/template/environment_hook/pythonpath.bat.in
- ament_package/template/package_level/local_setup.bat.in
- ament_package/template/package_level/local_setup.sh.in
- ament_package/template/prefix_level/local_setup.bat.in
- ament_package/template/prefix_level/setup.bat.in
- ament_package/templates.py
This addresses ament/ament_package#8.
> various changes to the Windows setup files

- ament_package/template/environment_hook/path.bat
- ament_package/template/environment_hook/pythonpath.bat.in
- ament_package/template/isolated_prefix_level/local_setup.bat.in
- ament_package/template/package_level/local_setup.bat.in
- ament_package/template/prefix_level/local_setup.bat.in
- ament_package/template/prefix_level/setup.bat.in
The patch makes no functional changes.
http://ci.ros2.org/job/ros2_batch_ci_windows/514/
> cleanup windows setup files

- ament_package/template/environment_hook/library_path.sh
In support of https://github.com/ament/ament_tools/pull/56
> add shared env hook for library path

- ament_package/template/isolated_prefix_level/local_setup.bat.in
- ament_package/template/isolated_prefix_level/local_setup.sh.in
- ament_package/template/prefix_level/local_setup.bat.in
- ament_package/template/prefix_level/local_setup.sh.in
http://ci.ros2.org/job/ros2_batch_ci_linux/534/
http://ci.ros2.org/job/ros2_batch_ci_osx/404/
http://ci.ros2.org/job/ros2_batch_ci_windows/559/
> fallback for Python executable

- ament_package/__init__.py
Fixes #32.
@jacquelinekay Please check if this addresses the problem for you.
> add manifest filename to exception if available

- ament_package/templates.py
- setup.py
Connect to ament/ament_cmake#63
> use pkg_resources to locate templates

- ament_package/template/prefix_level/setup.bat.in
- ament_package/template/prefix_level/setup.sh.in
Based on the discussion in http://discourse.ros.org/t/alpha8-hard-coded-paths/723
* http://ci.ros2.org/job/ci_linux/1818/
* http://ci.ros2.org/job/ci_windows/1730/
> replace {prefix} in the parent_prefix_path resource with the current prefix

- ament_package/template/isolated_prefix_level/local_setup.bat.in
> fix syntax

- ament_package/package.py
- ament_package/template/isolated_prefix_level/_order_isolated_packages.py
- ament_package/template/prefix_level/_order_packages.py
- ament_package/templates.py
- package.xml
- test/test_copyright.py
- test/test_flake8.py
- test/test_package.py
- test/test_pep257.py
Connect to ament/ament_index#25.
> use flake8 instead of pep8 and pyflakes

- ament_package/package.py
#51 introduced a test failure on this package. This fixes it
> add blankline between summary line and description

- ament_package/dependency.py
- ament_package/export.py
- ament_package/package.py
- ament_package/person.py
- ament_package/url.py
> implicitly inherit from object

- ament_package/__init__.py
- ament_package/dependency.py
- ament_package/package.py
- setup.py
- test/test_package.py
> update style to satisfy new flake8 plugins

- ament_package/template/environment_hook/pkg_config_path.bat
- ament_package/template/environment_hook/pkg_config_path.sh
Connect to ament/ament_tools#171.
> add PKG_CONFIG_PATH hook templates

- ament_package/group_dependency.py
Actually consider the condition when evaluating group memberships.
> consider condition for group membership

- ament_package/group_dependency.py
Reverts ament/ament_package#69
This broke master
See: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/lastFailedBuild/ and other nightlies
> Revert "consider condition for group membership"

- ament_package/group_dependency.py
Reapply #69.
Requires ament/ament_tools#178.
> consider condition for group membership - take 2

- ament_package/template/package_level/local_setup.sh.in
Resolves colcon/colcon-ros#67.
> add warning/fallback for AMENT_CURRENT_PREFIX if relocated

- setup.py
> install package manifest

- ament_package/template/prefix_level/local_setup.bat.in
Fixes #84.
Implementing this change: https://github.com/ament/ament_package/issues/84#issuecomment-538171105
> escape closing parenthesis in local_setup.bat file

- ament_package/template/prefix_level/local_setup.sh.in
> provide ament_prepend_unique_value function in prefix level sh script

- ament_package/template/prefix_level/_local_setup_util.py
Same as colcon/colcon-core#241.
> add type 'set' for dsv files

- setup.py
> [backport dashing] install resource marker file for package

- ament_package/template/isolated_prefix_level/local_setup.bat.in
- ament_package/template/prefix_level/local_setup.bat.in
> [backport dashing] add quotes around ament_python_executable variable in local_setup.bat

- ament_package/template/prefix_level/_local_setup_util.py
Useful for ros/ros_environment#19.
Same as colcon/colcon-core#250.
> add dsv type set-if-unset

- ament_package/template/prefix_level/_local_setup_util.py
Same as colcon/colcon-core#276.
> fixed KeyError in _prepend_unique_value

- ament_package/template/prefix_level/_local_setup_util.py
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9216)](http://ci.ros2.org/job/ci_linux/9216/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4907)](http://ci.ros2.org/job/ci_linux-aarch64/4907/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7516)](http://ci.ros2.org/job/ci_osx/7516/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9135)](http://ci.ros2.org/job/ci_windows/9135/)
* Windows-container [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=15)](http://ci.ros2.org/job/ci_windows-container/15/)
> use f-string

- ament_package/template/prefix_level/local_setup.bat.in
Same as colcon/colcon-core#348.
@seanyen FYI.
> [windows] fix _ament_python_executable fallback code path

- ament_package/template/prefix_level/local_setup.bat.in
- ament_package/template/prefix_level/setup.sh.in
> backports to Eloquent

- ament_package/template/isolated_prefix_level/local_setup.bash
- ament_package/template/isolated_prefix_level/local_setup.sh.in
- ament_package/template/isolated_prefix_level/local_setup.zsh
- ament_package/template/package_level/local_setup.bash.in
- ament_package/template/package_level/local_setup.sh.in
- ament_package/template/package_level/local_setup.zsh.in
- ament_package/template/prefix_level/local_setup.bash
- ament_package/template/prefix_level/local_setup.sh.in
- ament_package/template/prefix_level/local_setup.zsh
- ament_package/template/prefix_level/setup.bash
- ament_package/template/prefix_level/setup.sh.in
- ament_package/template/prefix_level/setup.zsh
Similar to colcon/colcon-core#403.
> make AMENT_TRACE_SETUP_FILES output sourceable

- ament_package/template/isolated_prefix_level/local_setup.bash
- ament_package/template/isolated_prefix_level/local_setup.sh.in
- ament_package/template/isolated_prefix_level/local_setup.zsh
- ament_package/template/package_level/local_setup.bash.in
- ament_package/template/package_level/local_setup.sh.in
- ament_package/template/package_level/local_setup.zsh.in
- ament_package/template/prefix_level/local_setup.bash
- ament_package/template/prefix_level/local_setup.sh.in
- ament_package/template/prefix_level/local_setup.zsh
- ament_package/template/prefix_level/setup.bash
- ament_package/template/prefix_level/setup.sh.in
- ament_package/template/prefix_level/setup.zsh
> [foxy] make AMENT_TRACE_SETUP_FILES output sourceable (#120)

- package.xml
I've added myself as a maintainer in all of the `package.xml`s.
> Add Audrow as a maintainer

- ament_package/generate_setuptools_dict.py
- package.xml
- test/test_generate_setuptools_dict.py
> [foxy] Generate Setuptools Dict Helper Method
