ament/ament_package

- ament_package/template/environment_hook/pythonpath.bat.in
- ament_package/template/isolated_prefix_level/local_setup.bat.in
- ament_package/template/package_level/local_setup.bat.in
- ament_package/template/prefix_level/local_setup.bat.in
- ament_package/template/prefix_level/setup.bat.in
- ament_package/templates.py
This pull request adds support for Windows by providing and exposing `.bat` versions of the `.sh` prefix level and package level `local_setup` and `setup` template files.
There is still work to be done here:
Connects to ros2/ros2#9
> Windows Support

- ament_package/templates.py
Currently only the Python code in `ament_tools` skips file extensions only relevant to other platforms. The `ament_cmake` packages don't. Therefore the `<prefix>` folder contains `setup.bash` as well as `setup.bat` which is bad for autocompletion.
Instead of spreading the filtering logic to multiple places the filter is now by default done withing `ament_package`. (Still with the option to get all extensions.)
@esteve @tfoote @wjwwood Please review.
Connects to ros2/ros2#19
> filter platform specific templates by default

- ament_package/__init__.py
If `pkg_resources` fails to import it was trying to `del` a non-existing variable.
I don't recall why the code was catching `OSError`. Since I don't see a use case for that I removed that as well.
@esteve @tfoote @wjwwood Please review.
> fix error when pkg_resources is not importable

- ament_package/template/prefix_level/setup.bat.in
- ament_package/template/prefix_level/setup.sh.in
Depends on ament/ament_cmake#17.
Also fixes the order when sourcing a workspace B which is built on top of a workspace A.
> use per package parent_prefix_path files, fix order of ament workspaces

- ament_package/template/prefix_level/local_setup.sh.in
- ament_package/template/prefix_level/setup.sh.in
To prevent cross talk between two separate source calls.
> unset AMENT_SHELL at the end of the scripts

- ament_package/template/package_level/local_setup.bash.in
- ament_package/template/package_level/local_setup.zsh.in
Before `AMENT_CURRENT_PREFIX` was not set in non-sh environment hooks since the previously sourced `local_setup.sh` file unsets the variable.
> fix AMENT_CURRENT_PREFIX available in non-sh shell environment hooks

- ament_package/template/isolated_prefix_level/local_setup.sh.in
- ament_package/template/package_level/local_setup.bash.in
- ament_package/template/package_level/local_setup.sh.in
- ament_package/template/package_level/local_setup.zsh.in
- ament_package/template/prefix_level/local_setup.sh.in
- ament_package/template/prefix_level/setup.sh.in
The first commit fixes #28.
The second commit unifies handling of IFS by always resetting it before souring other files.
> fix IFS cross talk

- ament_package/__init__.py
Otherwise `ament_package` won't parse the manifest file.
> accept schema attributes in manifest

- ament_package/template/prefix_level/local_setup.sh.in
Without this improvement, the alpha3 OS X binary returns this when I was testing it:
```
% source ./setup.zsh
/Users/william/testing_alpha3/ros2-osx/local_setup.sh:22: no such file or directory: /usr/bin/env python3
```
See related issue: https://github.com/ros2/ros2/issues/141
> improve python3 fallback executable logic in local_setup.sh

- ament_package/template/prefix_level/setup.bat.in
This is necessary to fix the environment when the `parent_path_prefix` file exceeds 1023 characters.
It works for me in the latest workspace: http://ci.ros2.org/job/ci_windows/868/
> fix handling of large parent path prefix files on Windows

- ament_package/__init__.py
- ament_package/export.py
- ament_package/package.py
- ament_package/person.py
- ament_package/templates.py
- ament_package/url.py
- test/test_package.py
Ensure that keyword args are actually be passed as keyword args.
CI passes: http://ci.ros2.org/job/ci_osx/747/
> prevent keyword arguments to be called as positional argument

- ament_package/__init__.py
Without this change, this is the error I get when building ROS2 inside a Docker container:
```
esteve@eobard:/tmp/ros2$ docker run -v `pwd`:/ros2 -w /ros2 ros2-ubuntu-xenial /ros2/src/ament/ament_tools/scripts/ament.py build --isolated --symlink-install
Traceback (most recent call last):
File "/ros2/src/ament/ament_tools/scripts/ament.py", line 149, in <module>
sys.exit(main() or 0)
File "/ros2/src/ament/ament_tools/ament_tools/commands/ament.py", line 88, in main
rc = args.main(args)
File "/ros2/src/ament/ament_tools/ament_tools/verbs/build/cli.py", line 142, in main
packages = topological_order(opts.basepath)
File "/ros2/src/ament/ament_tools/ament_tools/topological_order.py", line 103, in topological_order
packages = _find_unique_packages(root_dir)
File …
```
> Open package.xml file as UTF-8

- package.xml
With the schema for package manifests being available (ros-infrastructure/rep#117) we should start using them.
After this has been +1ed and merged I would propose to apply the same change to all other packages (without making PRs for the change though).
> add schema to manifest

- ament_package/template/isolated_prefix_level/local_setup.bat.in
This PR refers to https://github.com/ament/ament_package/issues/43.
It looks like the variable naming is not case sensitive so the script did not allow for the path to be overwritten. Finding python in the path and printing a helpful error was also added.
> added better features for finding python

- package.xml
When using ament_package on the test buildfarm it failed due to the missing package pkg_resources.
Here's [an example failure using an ament_package binary on a downstream package](http://test.build.ros2.org/view/Rbin_uX64/job/Rbin_uX64__ament_cmake_core__ubuntu_xenial_amd64__binary/3/console#console-section-15). Grep for ImportError to see the exact line.
```
23:01:26 -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.2", minimum required is "3") 
23:01:26 -- Using PYTHON_EXECUTABLE: /usr/bin/python3
23:01:26 -- ament_cmake_core 0.0.0
23:01:26 Traceback (most recent call last):
23:01:26   File "/tmp/binarydeb/ros-r2b2-ament-cmake-core-0.0.0/cmake/package_templates/templates_2_cmake.py", line 21, in <module>
23:01:26     from ament_package.templates import …
```
> Add setuptools dependency for pkg_resources

- ament_package/package.py
- test/test_package.py
If a package has a build type other than catkin or ament*, allow a dash in the name.
This mirrors the catkin change in ros-infrastructure/catkin_pkg#162 which enables support for the package name exceptions for dashes in http://www.ros.org/reps/rep-0140.html#name
The python here is pretty hairy as I'm still getting used to it. I'll be happy to restructure any of the changes here based on feedback.
> Allow dashes in non-catkin/ament* package names

- package.xml
From https://github.com/ros/rosdistro/pull/15328 there is no longer a rosdep key for `python3`.
All ament_python packages have injected build_depends on Debian packages python3-all, dh-python, and python3-setuptools.
The Debian package builder also adds python runtime dependencies as it sees fit via the `${python3:Depends}` helper.
I think there's a long term danger of too-closely relying on assumed dependencies, particularly for platform-specific builds, but for consistency with other ament_python packages I have removed these here.
If we want to leave these dependencies untouched in the source package.xml, they'll need to be patched out at release time since there is no longer a rosdep key `python3`.
> Remove python3 dependencies implied by ament_python build type.

- ament_package/template/prefix_level/_order_packages.py
Fixes #48.
I don't think this case needs a warning. If the prefix is empty or the packages didn't register themselves at the index that seems to be ok to me.
> check if path exists before trying to list dir

- ament_package/template/environment_hook/ament_prefix_path.bat
- ament_package/template/environment_hook/path.bat
- ament_package/template/environment_hook/pythonpath.bat.in
Work around different default installation path for Python scripts on Windows, see https://github.com/ament/ament_tools/pull/156#issuecomment-323198512.
Before: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3112)](http://ci.ros2.org/job/ci_windows/3112/)
After: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3113)](http://ci.ros2.org/job/ci_windows/3113/) (much further - but not all the way yet...)
> add Scripts to PATH on Windows

- ament_package/__init__.py
as I expect python-ament-package to never exist and hope we'll have python packages released without the ros namespace in the near future
> python-ament-package -> python3-ament-package

- ament_package/__init__.py
- ament_package/condition.py
- ament_package/dependency.py
- ament_package/group_dependency.py
- ament_package/group_membership.py
- ament_package/package.py
- test/test_package.py
Based on the current draft of [REP 149](https://github.com/ros-infrastructure/rep/pull/138).
> add support for package format 3

- ament_package/condition.py
- test/test_package.py
Implementing the change from ros-infrastructure/rep#146.
> support more operators in conditions

- package.xml
pyparsing was added to support the conditional dependency logic but was
never added as a dependency.
> Add pyparsing dependency for condition checking.

- ament_package/__init__.py
- ament_package/license.py
- test/test_package.py
Implemented https://github.com/ros-infrastructure/rep/pull/157.
Thanks.
> support file attribution of license tag

- package.xml
The code which required pyparsing was dropped in https://github.com/ament/ament_package/pull/75.
Incidentally it doesn't appear that the pyparsing dependency was ever added to setup.py. In general we want to keep setup.py and package.xml dependencies in sync right?
> Drop dependency on pyparsing.

- package.xml
- setup.py
Planning to tag the merged version of this commit as `0.5.1` in order to release it into Bouncy.
When bumping I noticed that the setup.py wasn't updated for 0.5.0. I bumped it here but I can undo that if it was intentionally left as is.
> Release 0.5.1

- ament_package/templates.py
Use raw strings for regex patterns to avoid warnings.
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=5348)](http://ci.ros2.org/job/ci_linux/5348/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=2078)](http://ci.ros2.org/job/ci_linux-aarch64/2078/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=4441)](http://ci.ros2.org/job/ci_osx/4441/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=5311)](http://ci.ros2.org/job/ci_windows/5311/)
> Fix lint warnings from invalid escape sequences

- package.xml
- setup.py
There isn't currently a changelog to update for this package so there's very little in this "draft" release commit except to notify that I'm making the release. Using 0.6.0 allows us room to make future changes to the 0.5.x track in bouncy.
> Prepare release of 0.6.0

- pytest.ini
The package doesn't depend on `ament_flake8` / `ament_lint` so these markers aren't defined. Since we still want to use them to select subset of tests and don't want to add a dependency for it this patch simply declares them for `pytest`.
> fix pytest warning about unknown markers

- ament_package/template/isolated_prefix_level/local_setup.bat.in
- ament_package/template/prefix_level/local_setup.bat.in
Fixes (update: no it doesn't) #84.
> add quotes around ament_python_executable variable in local_setup.bat

- ament_package/template/prefix_level/_local_setup_util.py
Follow up of #89. This will hopefully unbreak the binary jobs and "fix" the environment setup. It won't achieve the performance improvement though until the `package.dsv` files are generated in Debian packages.
> if no package.dsv is available fallback to a local_setup file

- ament_package/template/prefix_level/_local_setup_util.py
Follow up of #89. Fixes reading the run dependencies which always use a semicolon / CMake list separator - independent of the platform
> fix reading the package run dependencies

- .flake8
Follow up of #89. Fixes [linter warning](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1337/testReport/junit/ament_package.test/test_flake8/test_flake8/).
> keep using default ignore list

- ament_package/template/prefix_level/_local_setup_util.py
For example in a case where a package installs multiple jar files,
prepend-non-duplicate;CLASSPATH;share/pkg/foo.jar;/share/pkg/bar.jar
Similar to https://github.com/colcon/colcon-core/pull/247
> Add support for prepending multiple values to env variables from .dsv files

- ament_package/template/prefix_level/_local_setup_util.py
Fixes #103
Resolves the issue where environment variables can collide if they are modified by both .dsv files
and scripts. See the connected issue for more detail.
The solution is to always prepend to environment variables to avoid potentially overwriting a
value set from another script. To avoid a trailing separator we introduce a cleanup command that
is run for each variable prepended to.
> Always prepend with a trailing separator

- ament_package/template/prefix_level/_local_setup_util.py
Remove tailing semi-colon from "then;"
Also replace test command with "[" for clarity.
Introduced in #104.
Related colcon fix: https://github.com/colcon/colcon-core/pull/261
> Fix sh command to remove trailing separator

- ament_package/template/prefix_level/_local_setup_util.py
The trailing semicolon cleanup added in #104 was performed after every package. It only needs to happen once after all packages have finished.
> fix performance regression in environment setup

- ament_package/template/prefix_level/_local_setup_util.py
Which allows to group multiple lines if a `dsv` file updates more than one environment variable.
Same as colcon/colcon-core#275.
> skip empty lines in dsv files

- ament_package/template/prefix_level/_local_setup_util.py
Instead of showing a stacktrace print the filename and line number as well as a description what content was expected.
Same as colcon/colcon-core#277.
> improve error message when split for dsv line raises

- ament_package/template/prefix_level/_local_setup_util.py
- ament_package/template/prefix_level/local_setup.bat.in
Same as colcon/colcon-core#279.
> add missing quote around set arguments in bat

- ament_package/template/prefix_level/setup.sh.in
Related to ros2/ros2#929.
The diff is best looked at while ignoring indentation changes: https://github.com/ament/ament_package/pull/115/files?w=1
No CI since this isn't covered by it anyway but needs to be manually verified.
> add configure-time flag to skip parent_prefix_path

- ament_package/__init__.py
- ament_package/templates.py
- package.xml
As part of the switch away from pkg_resources (since it is
slow), we also need to fix up ament_package.  ament_package was using
'resource_filename' from pkg_resources.  The equivalent in
importlib is importlib.resources, but there is a catch.
As of Python 3.8, importlib.resources does not support getting
data from subdirectories.  The workaround is to make each
level of the directory structure a python module, so that the
module name can be looked up.  Python 3.9 will have support for
directories for resources, but that won't help on Ubuntu Focal.
More information is in https://gitlab.com/python-devs/importlib_resources/issues/58
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
See ros2/ros2#919 for a lot more details on why we want to do this.
> Switch ament_package to using importlib.

- package.xml
Requires ros/rosdistro#28001.
Used here:
https://github.com/ament/ament_package/blob/65e3322c5c668684dc973025bebbc70c6a77592f/ament_package/templates.py#L18-L21
The source code supports using the `importlib_resources` package, but on all of the platforms we're running regular builds for, we have Python 3.7, which provides the package as part of Python itself.
> Declare missing dependency on python3-importlib-resources

- ament_package/__init__.py
The `importlib_metadata` package is a backport of the `importlib.metadata` module from Python 3.8. Fedora (and possibly others) no longer package `importlib_metadata` because they ship Python versions which have the functionality built-in.
> Support Python 3.8-provided importlib.metadata

- ament_package/template/prefix_level/local_setup.bat.in
- ament_package/template/prefix_level/local_setup.sh.in
Part of https://github.com/ament/ament_cmake/pull/355, and should be merged with it. I think this is the minimum to get the prefix_level scripts working with `FindPython3`.
> Make python executable variable ament_package specific

- ament_package/template/package_level/local_setup.bat.in
- ament_package/template/package_level/local_setup.sh.in
- ament_package/template/prefix_level/_local_setup_util.py
- ament_package/template/prefix_level/local_setup.bat.in
It's currently possible to prepend unique values to environment variables. This change adds support for appending to them as well.
> Add support for appending to environment variables

- ament_package/template/prefix_level/_local_setup_util.py
Paris with colcon/colcon-core#550
This is a pretty containable change, and should be considered for backport to supported distros.
> Add support for comment lines in dsv files

- package.xml
It doesn't make sense for them to be <depend> in a pure Python package.
> Make python dependencies exec_depend.

- ament_package/templates.py
The `path()` function is deprecated.
https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy
For Python>=3.9, use `files()` instead.
> Migrate from legacy importlib-resources
